apps/curbside_concerts_web/lib/curbside_concerts_web/router.ex
defmodule CurbsideConcertsWeb.Router do
  use CurbsideConcertsWeb, :router

  alias CurbsideConcertsWeb.Plugs.AuthenticateUser
  alias CurbsideConcertsWeb.Plugs.SetCurrentUser

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug(SetCurrentUser)
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :requires_auth do
    plug AuthenticateUser
  end

  # This scope contains unauthenticated routes.
  scope "/", CurbsideConcertsWeb do
    pipe_through :browser

    # static home pages
    get "/", LandingController, :index
    get "/tips", MusicianController, :artists
    get "/perform", PerformController, :index
    get "/volunteer", LandingController, :volunteer

    # status pages
    get "/tracker/:tracker_id", RequestController, :tracker
    live "/session/driver/:driver_id", DriverLive, as: :session_route_driver
    get "/session/artist/:artist_id", SessionController, :session_route_artist

    # request management
    put "/cancel_request/:tracker_id", RequestController, :cancel_request
    get "/request/disclaimer", RequestController, :disclaimer
    # admin landing page
    get "/admin", AdminController, :index

    # authentication
    get("/sign-in", AccountSessionController, :new)
    post("/sign-in", AccountSessionController, :create)
  end

  # This scope contains authenticated routes.
  scope "/", CurbsideConcertsWeb do
    pipe_through [:browser, :requires_auth]

    # reports
    get "/reports/performances", ReportsController, :performances
    get "/reports/genres", ReportsController, :genres

    # session booker
    live "/session_booker/:session_id", SessionBookerLive, as: :session_booker

    # gig view
    get "/last_minute_gigs", RequestController, :last_minute_gigs
    get "/archived_requests", RequestController, :archived
    get "/gigs", RequestController, :index
    get "/gigs/:musician", RequestController, :index

    # request management
    get "/request/:id", RequestController, :show
    get "/request/:id/edit", RequestController, :edit
    put "/request/:id/update", RequestController, :update
    put "/request/:id/archive", RequestController, :archive
    put "/request/:id/unarchive", RequestController, :unarchive
    put "/request/:id/state/:state", RequestController, :state

    # musician management
    resources "/musician", MusicianController,
      only: [:create, :edit, :index, :new, :update, :show]

    # session management
    resources "/session", SessionController, only: [:create, :edit, :index, :new, :update, :show]
    get "/session/archived", SessionController, :index_archived
    put "/session/:id/archive", SessionController, :archive
    put "/session/:id/unarchive", SessionController, :unarchive

    # genre management
    resources "/genre", GenreController, only: [:index, :create, :edit, :new, :update, :show]
    put "/genre/:id/archive", GenreController, :archive
    put "/genre/:id/unarchive", GenreController, :unarchive

    # authentication
    delete("/sign-out", AccountSessionController, :delete)
  end

  if Mix.env() == :dev do
    forward "/sent_emails", Bamboo.SentEmailViewerPlug
  end

  # Other scopes may use custom stacks.
  # scope "/api", CurbsideConcertsWeb do
  #   pipe_through :api
  # end
end

apps/curbside_concerts_web/lib/curbside_concerts_web/controllers/request_controller.ex
defmodule CurbsideConcertsWeb.RequestController do
  @moduledoc """
  A controller for the request CRUD. This covers both creating a request on the
  requester side, and managing requests on the admin side.
  """

  use CurbsideConcertsWeb, :controller

  alias CurbsideConcerts.Requests
  alias CurbsideConcerts.Requests.Request
  alias CurbsideConcerts.Musicians
  alias CurbsideConcertsWeb.RequestView
  alias CurbsideConcertsWeb.TrackerCypher

  @spec new(Plug.Conn.t(), any) :: Plug.Conn.t()
  def new(conn, _params) do
    genres = Musicians.all_active_genres()

    changeset =
      Requests.change_request(%Request{
        genres: []
      })

    render(conn, "new.html", changeset: changeset, genres: genres)
  end

  @spec create(Plug.Conn.t(), map) :: Plug.Conn.t()
  def create(conn, %{"request" => request_params}) do
    case Requests.create_request(request_params) do
      {:ok, %Request{id: request_id, nominee_name: nominee_name}} ->
        tracker_id = TrackerCypher.encode(request_id)

        conn
        |> put_flash(
          :info,
          "Thank you for submitting a concert request for #{nominee_name}! Please bookmark this page to track its progress."
        )
        |> redirect(to: Routes.request_path(conn, :tracker, tracker_id))

      {:error, %Ecto.Changeset{} = changeset} ->
        data = Requests.load_genres(changeset.data)
        changeset = %{changeset | data: data}

        conn
        |> put_flash(
          :error,
          "Oops! Looks like a field is missing - please check below and try again"
        )
        |> render("new.html", changeset: changeset, genres: Musicians.all_genres())
    end
  end

  @spec index(Plug.Conn.t(), any) :: Plug.Conn.t()
  def index(conn, %{"musician" => gigs_id}) do
    musician = Musicians.find_musician_by_gigs_id(gigs_id)
    requests = Requests.get_by_gigs_id(gigs_id)

    conn
    |> assign(:requests, requests)
    |> assign(:musician, musician)
    |> render("musician_gigs.html")
  end

  def index(conn, %{"state" => state} = params) do
    conn
    |> assign(:state, state)
    |> assign(:request_type, RequestView.display_state(state))
    |> assign(:requests, Requests.all_active_requests_by_state(state))
    |> assign(:route, Routes.request_path(conn, :index, params))
    |> render("index.html")
  end

  def index(conn, _) do
    conn
    |> assign(:requests, Requests.all_active_requests())
    |> assign(:route, Routes.request_path(conn, :index))
    |> render("index.html")
  end

  @spec last_minute_gigs(Plug.Conn.t(), any) :: Plug.Conn.t()
  def last_minute_gigs(conn, _) do
    conn
    |> assign(:requests, Requests.all_last_minute_requests())
    |> assign(:request_type, "unbooked")
    |> assign(:route, Routes.request_path(conn, :last_minute_gigs))
    |> render("index.html")
  end

  def archived(conn, _) do
    conn
    |> assign(:requests, Requests.all_archived_requests())
    |> assign(:request_type, "archived")
    |> assign(:route, Routes.request_path(conn, :archived))
    |> render("index.html")
  end

  @spec tracker(Plug.Conn.t(), map) :: Plug.Conn.t()
  def tracker(conn, %{"tracker_id" => tracker_id}) do
    request_id = TrackerCypher.decode(tracker_id)
    request = Requests.find_request(request_id)

    conn
    |> assign(:tracker_id, tracker_id)
    |> assign(:request_id, request_id)
    |> assign(:request, request)
    |> render("tracker.html")
  end

  @spec cancel_request(Plug.Conn.t(), map) :: Plug.Conn.t()
  def cancel_request(conn, %{"tracker_id" => tracker_id}) do
    request_id = TrackerCypher.decode(tracker_id)
    request = Requests.find_request(request_id)

    if request != nil do
      Requests.cancel_request(request)

      conn
      |> put_flash(:info, "The concert request for #{request.nominee_name} has been cancelled.")
      |> redirect(to: Routes.request_path(conn, :new))
    else
      conn
      |> put_flash(:error, "The concert request was not found.")
      |> redirect(to: Routes.request_path(conn, :new))
    end
  end

  @spec show(Plug.Conn.t(), map) :: Plug.Conn.t()
  def show(conn, %{"id" => id}) do
    request = Requests.get_request(id, preloads: [:session, :genres])
    render(conn, "show.html", request: request)
  end

  @spec edit(Plug.Conn.t(), map) :: Plug.Conn.t()
  def edit(conn, %{"id" => id}) do
    genres = Musicians.all_active_genres()
    request = Requests.get_request(id, preloads: [:session, :genres])
    changeset = Requests.change_request(request)
    render(conn, "edit.html", request: request, genres: genres, changeset: changeset)
  end

  @spec update(Plug.Conn.t(), map) :: Plug.Conn.t()
  def update(conn, %{"id" => id, "request" => request_params}) do
    request = Requests.find_request(id)

    case Requests.update_request(request, request_params) do
      {:ok, request} ->
        conn
        |> put_flash(:info, "Request updated successfully.")
        |> redirect(to: Routes.request_path(conn, :show, request))

      {:error, %Ecto.Changeset{} = changeset} ->
        genres = Musicians.all_active_genres()
        render(conn, "edit.html", request: request, genres: genres, changeset: changeset)
    end
  end

  @spec archive(Plug.Conn.t(), map) :: Plug.Conn.t()
  def archive(conn, %{"id" => id, "redirect" => redirect}) do
    request = Requests.get_request(id)
    {:ok, _request} = Requests.archive_request(request)

    conn
    |> put_flash(:info, "Request archived successfully.")
    |> redirect(to: redirect)
  end

  @spec unarchive(Plug.Conn.t(), map) :: Plug.Conn.t()
  def unarchive(conn, %{"id" => id, "redirect" => redirect}) do
    request = Requests.get_request(id)
    {:ok, _request} = Requests.unarchive_request(request)

    conn
    |> put_flash(:info, "Request unarchived successfully.")
    |> redirect(to: redirect)
  end

  @doc """
  This route can be used to change the status of a request.

  Path: "/request/:id/state/:state?redirect=:redirect_url"

  Parameters:
  - id: the id of a request
  - state: the string corresponding to a valid request state
  - redirect: the route that should be redirected to after updating the request

  Sample Usage:

  ```
  Routes.request_path(
  	CurbsideConcertsWeb.Endpoint,
  	:state,
  	request,
  	"pending",
  	%{redirect: Routes.request_path(CurbsideConcertsWeb.Endpoint, :index)}
  )
  ```
  """
  @spec state(Plug.Conn.t(), map) :: Plug.Conn.t()
  def state(conn, %{"id" => id, "state" => state, "redirect" => redirect}) do
    request = Requests.get_request(id)

    case state do
      "offmission" -> Requests.off_mission_request(request)
      "pending" -> Requests.back_to_pending_request(request)
      _ -> nil
    end

    conn
    |> put_flash(:info, "Request state updated successfully.")
    |> redirect(to: redirect)
  end

  @spec disclaimer(Plug.Conn.t(), any) :: Plug.Conn.t()
  def disclaimer(conn, _params) do
    render(conn, "disclaimer.html")
  end
end

apps/curbside_concerts_web/lib/curbside_concerts_web/templates/request/disclaimer.html.eex
<div class="card card-with-nav">
	<%= LayoutView.render_nav_links(LayoutView.get_nav_links("REQUEST")) %>
	
  <header class="request-form">
		<h2>Disclaimer</h2>
  </header>

  <p>
    Curbside Concerts is a project by Can't Stop Columbus ("CSCBUS"), an initiative of Smart Columbus, LLC and the Columbus Partnership, a 501(c)(3) nonprofit organization. 
  </p>
  <p>
    IN CONSIDERATION FOR THE SERVICES PROVIDED BY THE CURBSIDE CONCERTS PROJECT, YOU AGREE TO WAIVE AND HOLD HARMLESS CSCBUS, SMART COLUMBUS, AND THE COLUMBUS PARTNERSHIP, TOGETHER WITH THEIR VOLUNTEERS, OFFICERS, DIRECTORS, EMPLOYEES, CONTRACTORS, AGENTS, LICENSORS, SUPPLIERS, PARTNERS, AFFILIATES, OWNERS, SUCCESSORS AND ASSIGNS FROM ANY AND ALL CLAIMS, CAUSES OF ACTION, DEMANDS, LIABILITIES, DAMAGES, JUDGMENTS, AWARDS, LOSSES, COSTS, EXPENSES, OR FEES (INCLUDING REASONABLE ATTORNEYS' FEES), WHETHER IN TORT OR IN CONTRACT, BOTH KNOWN AND UNKNOWN, IN LAW OR IN EQUITY, AGAINST CSCBUS, SMART COLUMBUS, AND THE COLUMBUS PARTNERSHIP ARISING OUT OF THE SERVICES PROVIDED.
  </p>
</div>



apps/curbside_concerts_web/lib/curbside_concerts_web/templates/request/edit.html.eex
<div class="card">
  <h1>Edit Request</h1>
  <%= request_list_links() %>
</div>

<div class="card">
  <%= form_for @changeset, Routes.request_path(@conn, :update, @changeset.data), fn f -> %>
    <%= hidden_input f, :id %>
    <%= unless f.errors == [], do: inspect(f.errors) %>

    <label class="field">Priority: <%= request_checkbox f, :priority %></label>
    <label class="field">Admin Notes: <%= textarea f, :admin_notes %></label>

    <label class="field">Deprecated Address: <%= input_value(f, :nominee_address) %></label>

    <label class="field">Nominee Street Address: <%= text_input f, :nominee_street_address %></label>
    <label class="field">Nominee City: <%= text_input f, :nominee_city %></label>
    <label class="field">Nominee Zip Code: <%= text_input f, :nominee_zip_code %></label>
    <label class="field">Nominee Address Notes: <%= textarea f, :nominee_address_notes %></label>

    <label class="field">Nominee Name: <%= request_input f, :nominee_name %></label>
    <label class="field">Request Reason: <%= request_input f, :request_reason %></label>
    <label class="field">Nominee Description: <%= request_input f, :nominee_description %></label>

    <label class="field">Special Message: <%= request_input f, :special_message %></label>
    <label class="field">Sender Name: <%= request_input f, :special_message_sender_name %></label>


    <label class="field">Request Occasion: <%= request_input f, :request_occasion %></label>

    <label class="field">Special Day: <%= request_date f, :preferred_date, "Select Special Day (optional)" %></label>


    <label class="field">Genres:
      <%= multiselect_checkboxes(
          f,
          :genres,
          Enum.map(@genres, fn a -> { a.name, a.id } end),
          selected: Enum.map(@changeset.data.genres,&(&1.id))
      )%>
    </label>


    <label class="field">Favorite Music: <%= request_input f, :nominee_favorite_music_notes %></label>

    <label class="field">Requester Name: <%= request_input f, :requester_name %></label>
    <label class="field">Requester Relationship: <%= request_input f, :requester_relationship %></label>

    <label class="field">Requester Email: <%= request_input f, :requester_email, type: :email %></label>
    <label class="field">Newsletter Opt In: <%= request_checkbox f, :requester_newsletter_interest %></label>

    <label class="field">Requester Phone: <%= request_input f, :requester_phone, type: :phone %></label>

    <label class="field">Contact Preference: <%= contact_preference_radio f %></label>
    <label class="field">Nominee Phone: <%= request_input f, :nominee_phone, type: :phone %></label>
    <label class="field">Nominee Email: <%= request_input f, :nominee_email, type: :email %></label>

    <label class="field">Special Instructions: <%= request_input f, :special_instructions %></label>
    <button type="submit">SUBMIT</button>
  <% end %>
</div>

apps/curbside_concerts_web/lib/curbside_concerts_web/templates/request/index.html.eex
<div class="card">
  <h1>All<%= if assigns[:request_type], do: " #{assigns[:request_type]}", else: "" %> requests (<%= length(@requests) %>)</h1>
    <%= link "Back to Admin", to: Routes.admin_path(@conn, :index) %>
    <br>
    Other Request Lists: <%= CurbsideConcertsWeb.RequestView.request_list_links() %>
  </div>

  <%= for %Request{
      inserted_at: inserted_at,
      genres: genres,
      state: _state,
      contact_preference: _contact_preference,
      nominee_name: nominee_name,
      nominee_description: nominee_description,
      request_reason: request_reason,
      nominee_street_address: _nominee_street_address,
      nominee_city: _nominee_city,
      nominee_zip_code: _nominee_zip_code,
      nominee_address_notes: nominee_address_notes,
      nominee_phone: nominee_phone,
      special_message: special_message,
      special_message_sender_name: special_message_sender_name,
      requester_name: requester_name,
      requester_relationship: requester_relationship,
      requester_email: requester_email,
      requester_phone: requester_phone,
      archived: archived?,
      priority: priority?,
      nominee_favorite_music_notes: favorite_notes,
      request_occasion: occasion,
      preferred_date: preferred_date,
      nominee_email: nominee_email,
      special_instructions: special_instructions,
      requester_newsletter_interest: _newsletter_interest?,
      admin_notes: admin_notes
		} = request <- @requests do %>

    <div class="card <%= if priority?, do: "priority-request" %>">
      <%= if admin_notes do %>
        <div class="admin-notes-display"><%= admin_notes %></div>
      <% end %>
      <div><b>Preferred Date:</b> <%= preferred_date %></div>
      <div><b>Request Occasion:</b> <%= occasion %></div>
      <div><b>Request Reason:</b> <%= request_reason %></div>
      <div><b>Nominee Description:</b> <%= nominee_description %></div>
      <div><b>Status:</b> <%= display_state(request) %> <%= if archived?, do: "ARCHIVED" %></div>
      <div><b>Date of Request:</b> <%= inserted_at %></div>

      <br>

      <div><b>Contact Preference:</b> <%= contact_preference(request) %></div>

      <br>

      <div>
        <b>Map to <%= nominee_name %>'s house:</b>
        <a href="http://maps.google.com/?q=<%= URI.encode(RequestAddress.full_address(request)) %>"><%= RequestAddress.full_address(request) %></a>
      </div>

      <%= if nominee_address_notes do %>
        <div>
          <b>Address Instructions:</b><br>
          <%= raw nominee_address_notes %>
        </div>
      <% end %>

      <%= if special_instructions do %>
        <div>
          <b>Special Instructions:</b><br>
          <%= raw special_instructions %>
        </div>
      <% end %>

      <%= if favorite_notes do %>
        <div>
          <b>Favorite Music Notes:</b><br>
          <%= raw favorite_notes %>
        </div>
      <% end %>

      <br>

      <div style="display: flex">
        <div style="margin-right: 16px">
          <b>To:</b><br>
          <%= nominee_name %><br>
          <%= nominee_phone %><br>
          <%= nominee_email %>
        </div>
        <div>
          <b>From:</b><br>
          <%= requester_name %><br>
          <%= requester_relationship %><br>
          <%= requester_phone %><br>
          <%= requester_email %>
        </div>
      </div>
      <br>
      <div>
        <b>Preferred Genres:</b>
        <ul>
          <%= for %Genre{name: name} <- genres do %>
            <li><%= name %></li>
          <% end %>
        </ul>
      </div>
      <div><b>Special Message:</b><br>
        <%= raw special_message %>
        <%= if special_message_sender_name do %>
          <br> - <%= special_message_sender_name  %>
        <% end %>
      </div>

      <br />

      <div>
        <%= link "View", to: Routes.request_path(CurbsideConcertsWeb.Endpoint, :show, request) %>
        | <%= request_action_links(request, @route) %>
        | <%= requester_tracker_link(request) %>
      </div>
    </div>

  <% end %>

apps/curbside_concerts_web/lib/curbside_concerts_web/templates/request/musician_gigs.html.eex
<h1>All requests for <%= @musician.name %></h1>

<div class="card">
  <%= map_route_link(@requests) %>
</div>

<%= request_cards(@conn, @requests) %>

apps/curbside_concerts_web/lib/curbside_concerts_web/templates/request/new.html.eex
<%= form_for @changeset, Routes.request_path(@conn, :create), fn f -> %>
<div class="card card-with-nav">
	<%= LayoutView.render_nav_links(LayoutView.get_nav_links("REQUEST")) %>

  <header class="request-form">
    <h1>Request a Curbside Concert</h1>
		<h2>Fill out the form below to make your request for a 2020 Hero.</h2>
    <p>
			<strong>Note</strong>: priority will be given to heroes based on the message you share, the requested location, and schedule availability. We currently aren’t able to fulfill requests that are outside the Central Ohio area.
		</p>
  </header>
</div>

<div class="request-form card">
  <h2>Your nominee</h2>
  <p>Curbside Concerts isn’t just “live music on demand”... it's meant to be a medium for you to reach out and send a delightful experience to someone who has done extraordinary things in a very difficult year.  Our musicians do their best to tailor their performances to each nominee... help us get to know yours.</p>
  <label class="field">
    <div>First and last name(s) of who you are sending this concert to. <%= required_star() %></div>
    <%= request_input f, :nominee_name %>
  </label>
  <label class="field">
    <div>Why are you compelled to send a concert to this person? Please explain how your nominee has been a Hero in 2020. <%= required_star() %></div>
    <%= request_input f, :request_reason %>
  </label>
</div>

<div class="request-form card">
  <h2>Your message</h2>
  <p>During their performance, our artist will share that this concert was sent by you and will read what you type below.
  Please write a heartfelt message to your nominee so our artist can relay your kindness, voice and well-wishes (e.g. "I appreciate you because" or "I am thinking about you and the time we...”)</p>
  <label class="field">
    <div>Write a message that you would like to have read aloud by the artist on your behalf to your nominee: <%= required_star() %></div>
    <%= request_input f, :special_message %>
  </label>
  <label class="field">
    <div>Who should we say this message is from? <%= required_star() %></div>
    <p class="negative">(e.g. their favorite son, oldest friend, most talented co-worker, member of church community, etc.)</p>
    <%= request_input f, :special_message_sender_name %>
  </label>
</div>

<div class="request-form card">
  <h2>The concert</h2>
  <p class="field">While we can’t guarantee a specific time, date or musician, if you give us some details about what could make this performance extra special, we’ll do our best to make it happen. We have a long list of outstanding requests and we do not schedule in order of receipt but rather by location.</p>
  <label class="field">
    <div>Is there a specific purpose, situation or meaningful occasion we should attempt to schedule around?  Are there days or times that do not work?</div>
    <p class="negative">(e.g. birthday, wedding anniversary, recovering from an illness, etc.)</p>
    <%= request_input f, :request_occasion %>
  </label>
  <label class="field">
    <div>Is having the concert on a specific date really important? Please note: We are currently only booking concerts Friday-Sunday.</div>
    <p class="negative">(Note: if a specific day isn’t essential, do not not fill out this date as that will increase our ability to book your request. If you do select a date and we can’t book that date, we won’t book your request).</p>
    <%= request_date f, :preferred_date, "Select Special Day (optional)" %>
  </label>
  <br/>
  <div>Which type of music would your nominee enjoy hearing at their Curbside Concert? (please check all that apply):  </div>
  <p>Although we will do our best, we can’t promise we’ll be able to get an artist who can play to your exact requests.</p>
  <%= multiselect_checkboxes(
      f,
      :genres,
      Enum.map(@genres, fn a -> { a.name, a.id } end),
      selected: Enum.map(@changeset.data.genres,&(&1.id))
  )%>
</div>

<div class="request-form card">
  <h2>The location</h2>
  <p class="field">We’ll pull up in a pick-up and will be following all social distancing guidelines. Given that, Curbside Concerts are best held at homes / apartments / neighborhoods where your nominee can safely enjoy the show from a patio, yard, driveway, side street, balcony or shared outdoor common space. If that is not possible, please reconsider your request (don’t worry about the neighbors... odds are, they’ll join in on the fun :-) ).</p>
  <label class="field">
    <div>Street Address <%= required_star() %></div>
    <p class="negative">Provide a specific address where we will play for your nominee (e.g. their home)</p>
    <%= request_input f, :nominee_street_address %>
  </label>
  <div id="address_container">
    <label>
      <div>City  <%= required_star() %></div>
      <%= request_input f, :nominee_city %>
    </label>
    <label>
      <div>Zip Code  <%= required_star() %></div>
      <%= request_zip f, :nominee_zip_code %>
    </label>
  </div>
  <label class="field">
    <div>Any special instructions?</div>
    <p class="negative">List any relevant details about the location and/or logistics that can help our driver get in the right spot (e.g. park near the lawn to the left, code to get through a gate, she’ll be sitting on the second floor balcony, etc.)</p>
    <%= request_input f, :nominee_address_notes %>
  </label>
</div>

<div class="request-form card">
  <h2>A little bit about you</h2>
  <p class="field">Our goal is to keep you as up-to-date as possible about when the concert will happen, so you can choose how to let your nominee know (e.g. set it up as a surprise, ensure they’ll be at home, or tell some of the neighbors in advance).</p>
  <label class="field">
    <div>Your first and last name <%= required_star() %></div>
    <%= request_input f, :requester_name %>
  </label>
  <label class="field">
    <div>What is your relationship to the nominee?</div>
    <p class="negative">(e.g. their favorite son, oldest friend, most talented co-worker, member of church community, etc.)</p>
    <%= request_input f, :requester_relationship %>
  </label>
  <label class="field">
    <div>Please provide your email address to receive notification of when your request has been booked: <%= required_star() %></div>
    <%= request_input f, :requester_email, type: :email %>
    <p class="negative"><%= request_checkbox f, :requester_newsletter_interest %> Please check here to receive Can’t Stop Columbus’ weekly newsletter, and stay up-to-date on all the great things happening in our community.</p>
  </label>
  <label class="field">
    <div>Please provide a mobile phone number to receive a text message alert on the day of the performance <%= required_star() %></div>
    <%= request_input f, :requester_phone, type: :phone %>
  </label>
</div>

<div class="request-form card">
  <h2>Getting in touch</h2>
    <p class="negative">While on our route, we'll call or text ahead when we're on our way (about 15 to 45 minutes before we arrive).</p>
  <label class="field">
    <div>How do you want us to contact the nominee? <%= required_star() %></div>
    <p class="negative">Given that some folks can be skeptical of calls, you have the option for us to contact you, or the nominee – please choose an option below</p>
    <%= contact_preference_radio f %>
  </label>
  <label class="field">
    <div>If you chose "Call the nominee" above, please provide their phone number:</div>
    <%= request_input f, :nominee_phone, type: :phone %>
  </label>
  <label class="field">
    <div>Please provide the nominee’s email address so we can ask a few follow up questions about their experience:</div>
    <%= request_input f, :nominee_email, type: :email %>
  </label>
</div>



<div class="request-form card">
  <label class="field">
    <div>Anything else we should know about your request?</div>
    <%= request_input f, :special_instructions %>
  </label>
</div>

<div class="request-form">
  <p id="disclaimer">By requesting a concert, I agree to <%= link "the following disclaimer.", to: Routes.request_path(@conn, :disclaimer), target: "_blank" %></p>
  <button type="submit">SUBMIT</button>
</div>
<% end %>

apps/curbside_concerts_web/lib/curbside_concerts_web/templates/request/show.html.eex
<div class="card">
  <h1>View Request</h1>
  <%= request_list_links() %>
</div>

<div class="card">
  <%= render "request_card.html", request: @request, conn: @conn %>
</div>